services:
  postgres_db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_DB=legira_db
      - POSTGRES_USER=amarchuk
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"

